---
- hosts: all
  sudo: true
  tasks:
    - name: update apt packages
      apt: update_cache=yes

    - name: ensure git installed
      apt: name=git state=present
  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_rubyies:
        = 'ruby-2.2.2'
